### ISSUE TITLE
Finance : Export All LOBs

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#37]

**Comment by csoroka** [comment]
I ran the Export All LOBs report.  I compared each company tab, for the 2022 Org Budget, for the new prod vs the current prod.  The number of row differs but I believe that is due to zero rows being eliminated in the new prod.
The totals match for all companies **but FDN**.
The FDN tab is showing positive numbers for the revenue accounts instead negative numbers (see other company tabs for comparison)

**Comment by kclark-a3** [comment]
What is the issue?

**Comment by kclark-a3** [comment]
update

The FDN tab is showing positive numbers for the revenue accounts instead negative numbers (see other company tabs for comparison) **this was fixed**

**Comment by csoroka** [comment]
tested and FDN now matches - looks good
