### ISSUE TITLE
Scenario: Remove the Scenario type tag

### ISSUE THREAD

**Issue by rlautt** [afs1jes/CHNCT-Migration#61]

**Comment by afs1jes** [comment]
This issue is related to how A3 Modeling queries Transaction records. Any drill to transactions will ignore the member from the dimension marked as type Scenario. The assumption is that transactions will only exist in one scenario and is, therefore, irrelevant when querying. In some case, transactions may be associated with more scenario members, meaning that the query needs to include the scenario member name as it asks for the transactions.   

This change was required to prevent the appearance that transactions had been duplicated after data copies that also copy transactions to different scenarios. In this case, drilling to transactions from a scenario that is not "Actuals" will return only transactions that had been copied into that scenario.
